const COMMENTS_QUANTITY = 5;

const MAX_HASHTAG_QUANTITY = 5;

const VALID_SYMBOLS = /^#[a-zа-яë0-9]{1,19}$/i;

const DEFAULT_SCALE = 100;

const SCALE_STEP = 25;

const MIN_SCALE = 25;

const MAX_SCALE = 100;

const ALERT_SHOW_TIME = 5000;

const TIMEOUT__DELAY = 500;

const RANDOM__IMAGES__QUANTITY = 10;

export {COMMENTS_QUANTITY, MAX_HASHTAG_QUANTITY, VALID_SYMBOLS, DEFAULT_SCALE,
  SCALE_STEP, MIN_SCALE, MAX_SCALE, ALERT_SHOW_TIME,
  TIMEOUT__DELAY, RANDOM__IMAGES__QUANTITY};
