const COMMENTS_QUANTITY = 5;

const MAX_HASHTAG_QUANTITY = 5;

const VALID_SYMBOLS = /^#[0-9A-ZА-ЯЁ]{1,19}$/i;

const DEFAULT_SCALE = 100;

const SCALE_STEP = 25;

const MIN_SCALE = 25;

const MAX_SCALE = 100;

const ALERT_SHOW_TIME = 5000;

const TIMEOUT_DELAY = 500;

const RANDOM_IMAGES_QUANTITY = 10;

const PERCENTAGE = 100;

const INITIAL_SCALE = 100;

export {COMMENTS_QUANTITY, MAX_HASHTAG_QUANTITY, VALID_SYMBOLS, DEFAULT_SCALE,
  SCALE_STEP, MIN_SCALE, MAX_SCALE, ALERT_SHOW_TIME,
  TIMEOUT_DELAY, RANDOM_IMAGES_QUANTITY, PERCENTAGE, INITIAL_SCALE};
